---
## This is used for the local server name, your hosts file, and the name in the virtual box registry
hostname: "local.dev"

## Make sure that this IP is not in use on your system currently
private_network_ip: "172.28.150.10"

## 2048mb - or 2 gigs RAM is available to the virtual machine
available_ram_mb: 2048

## enable swap on this machine.  Probably not used unless you have very low RAM available for this
enable_swap: no

# Extra Items

install_composer: true
install_apidoc: true
install_jsdoc: true
install_composer: true
install_wordpress: false
install_drupal: false