---
- name: Write swapfile
  command: fallocate -l 4G /swapfile creates=/swapfile
  register: write_swapfile

- name: Set swapfile permissions
  file: path=/swapfile mode=600

- name: Create swapfile
  command: mkswap /swapfile
  register: create_swapfile
  when: write_swapfile.changed

- name: Enable swapfile
  command: swapon /swapfile
  when: create_swapfile.changed

- name: Add swapfile to /etc/fstab
  lineinfile: dest=/etc/fstab line="/swapfile   none    swap    sw    0   0" state=present

- name: Configure vm.swappiness
  sysctl: name=vm.swappiness value=10 state=present reload=yes

- name: Configure vm.vfs_cache_pressure
  sysctl: name=vm.vfs_cache_pressure value=50 state=present reload=yes
