---
- name: Install PHP and its modules
  apt: pkg={{ item }} state=latest
  with_items:
    - php5
    - php5-cli
    - php5-mysql
    - php5-imagick
    - php5-curl
    - php5-gd
    - php5-sqlite
  notify:
    - restart apache

- name: Set display_errors on
  lineinfile: dest=/etc/php5/apache2/php.ini regexp=^display_errors line='display_errors = On'
  notify:
    - restart apache

- name: Set upload_max_filesize
  lineinfile: dest=/etc/php5/apache2/php.ini regexp=^upload_max_filesize line='upload_max_filesize = 20M'
  notify:
    - restart apache

- name: Set session save path to /tmp
  lineinfile: dest=/etc/php5/apache2/php.ini regexp=^;?session.save_path line='session.save_path = "/tmp"'
  notify:
    - restart apache

- name: Make sure CLI logs to syslog
  lineinfile: dest=/etc/php5/cli/php.ini regexp=^;?error_log line='error_log = syslog'

- name: Delete the cron php file
  file: path=/etc/cron.d/php5 state=absent

- name: Set session garbage collection on
  lineinfile: dest=/etc/php5/apache2/php.ini regexp=^session.gc_probability line='session.gc_probability = 1'
  notify:
    - restart apache

- include: composer.yml